/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.symbol;

import java.util.*;
import golite.node.*;
import golite.analysis.*;

public class SymbolTableBuilder extends DepthFirstAdapter
{
    private SymbolTable symbolTable;

    public SymbolTable getSymbolTable() {
        return symbolTable;
    }

    @Override //Modified
    public void inStart(Start node) 
    {
        symbolTable = new SymbolTable();
        symbolTable.enterScope();
    }

    @Override //Modified
    public void caseAFuncTopDec(AFuncTopDec node)
    {
        symbolTable.addSymbol(node.getId().getText(), node);
    }

    @Override //Modified
    public void caseASpecVarSpec(ASpecVarSpec node)
    {
        {
            List<TId> copy = new ArrayList<TId>(node.getId());
            for(TId e : copy)
            {
                symbolTable.addSymbol(e.getText(), node);
            }
        }
    }

    @Override //Modified
    public void caseASpecTypeSpec(ASpecTypeSpec node)
    {
        symbolTable.addSymbol(node.getId().getText(), node);
    }
}
